### ISSUE TITLE
Wrong pinout for ESP32-C3 module

### ISSUE THREAD

**Issue by danielkucera** [AchimPieters/pinout#1]
in this file:  pinout/ESP32-C3/ESP-C3-12F Module PINOUT.pdf the pinout is wrong. Pins GPIO6 and GPIO7:
![image](https://user-images.githubusercontent.com/1734256/196757317-712e812a-3987-4376-9313-85429e1411fa.png)

**Comment by AchimPieters** [comment]
@danielkucera Fixed in https://github.com/AchimPieters/pinout/blob/main/ESP32-C3/ESP-C3-12F%20Module%20PINOUT_v2.1.2pdf.pdf

**Comment by danielkucera** [comment]
Thanks. You still have the wrong image here: https://www.studiopieters.nl/esp32-c3-pinout/
